import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Domine } from "next/font/google";
import { Montserrat } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css';
import { Poppins } from 'next/font/google'
import { SidebarProvider } from "@/context/SidebarContext";
import { Toaster } from "@/components/ui/toaster";
 
const roboto = Poppins({
  weight: '500',
  subsets: ['latin'],
  display: 'swap',
})
// const roboto = Open_Sans({
//   weight: '400',
//   subsets: ['latin'],
//   display: 'swap',
// })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className={roboto.className} >
      <Toaster/>
      <SidebarProvider>

        {children}
        
        </SidebarProvider>

        </body>
    </html>
  );
}
